name: Prefix
authors: [MountCloud]
website: http://www.mountcloud.org
description: Prefix is a plugin for the player name prefix.

#使用mc-plugin-common必须设置依赖关系为 [McPluginCommon]，use mc-plugin-common must set the dependency [McPluginCommon]
depend: [McPluginCommon]

main: org.mountcloud.mcplugin.prefix.PrefixPluginMain
version: 1.0
commands:
 prefix:
  description: prefix
  usage: /prefix